name: Security Scan

on:
  workflow_dispatch:

jobs:
  trivy_scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-report.sarif'
          scanners: 'vuln,misconfig,secret,license'
          # skip-dirs: './venv'
          cache: 'false'
      
      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.sarif
      
      - name: Upload Trivy report to GitHub code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-report.sarif
        if: always()

  semgrep_scan:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run Semgrep Scan
        run: semgrep scan -q --sarif --config auto ./ > semgrep-report.sarif
      
      - name: Upload Semgrep report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-report.sarif

      - name: Upload Semgrep results to GitHub code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-report.sarif
        if: always()
