# name: On-Demand Security Scan

# on:
#   workflow_dispatch:

# jobs:
#   trivy_scan:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Install Trivy
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y wget
#           wget -qO- https://github.com/aquasecurity/trivy/releases/latest/download/trivy_$(uname -s)_$(uname -m).tar.gz | tar xz
#           sudo mv trivy /usr/local/bin/
#       - name: Run Trivy on Root Directory
#         run: |
#           trivy fs --scanners vuln,misconfig,secret,license --report all --format json --output trivy-report.json --skip-dirs ./venv ./
#       - name: Upload Trivy Report
#         uses: actions/upload-artifact@v4
#         with:
#           name: trivy-report
#           path: trivy-report.json

#   semgrep_scan:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Install Semgrep
#         run: pip install semgrep
#       - name: Run Semgrep on Root Directory
#         run: semgrep scan --config=auto --output semgrep-report.json --json ./
#       - name: Upload Semgrep Report
#         uses: actions/upload-artifact@v4
#         with:
#           name: semgrep-report
#           path: semgrep-report.json


name: Security Scan

on:
  workflow_dispatch:

jobs:
  trivy_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy filesystem scan (root)
        # Use the official Trivy GitHub Action for best compatibility and no manual install hassles
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'json'
          output: 'trivy-report.json'
          scanners: 'vuln,misconfig,secret,license'
          skip-dirs: './venv'
      
      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json

  semgrep_scan:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run Semgrep scan (root directory)
        run: semgrep scan -q --sarif --config auto ./ > semgrep-report.sarif
      
      - name: Upload Semgrep report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-report.sarif

      - name: Upload Semgrep results to GitHub code scanning (optional)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-report.sarif
        if: always()
